### ISSUE TITLE
100+ puppets overloads the extension

### ISSUE THREAD

**Issue by Riael** [NationStates/NationStatesPlusPlus#11]
I've noticed that while having around... 130 puppets in the sidebar of the addon for fast switching it glitches out. A LOT. Takes about 20 tries (closing reopening the tab and/or the browser) for a button to work, then sometimes when it switches me to another nation even if I didn't plan on that, and lags, a log, besides that I can not see all the puppets at once.

**Comment by Afforess** [comment]
The extension will no longer try to render very long lists of puppets and instead warn the user.

Fixed in https://github.com/NationStates/NationStatesPlusPlus/commit/16ddaf27b29282c8c243871261261d39a39d5396
