### ISSUE TITLE
Add Select All button to Puppet Manager

### ISSUE THREAD

**Issue by Eluvatar** [NationStates/NationStatesPlusPlus#16]
The shift-select method may be intuitive enough to /expect/ users to understand it, but some don't, and as the most common use case it may make sense to reduce the complexity of the operation for the user.

Not urgent.

**Comment by Afforess** [comment]
Implemented here: https://github.com/NationStates/NationStatesPlusPlus/commit/e314aaf32fb6676806adca3851fcb85316d40fc4
