### ISSUE TITLE
Able to Access Regional Controls

### ISSUE THREAD

**Issue by nitro740** [NationStates/NationStatesPlusPlus#28]
With the new update (?) that added the "Board," "Activity," "History," and "Admin" buttons to the Region homepage, it also appears that access to the "Regional Controls" button is given when NS++ is activated. I have not tried editing anything, mainly because I am afraid that it will work. Here are a couple of screenshots of the Region homepage with and without NS++, and what happens when "Regional Controls" is selected.

![trelark regional controls bug 1](https://cloud.githubusercontent.com/assets/5599436/6568869/8e7d538e-c69c-11e4-99be-6c095a4c62e5.png)
![trelark regional controls bug 2](https://cloud.githubusercontent.com/assets/5599436/6568868/8bc1a7d0-c69c-11e4-9411-cbe13126ae20.png)
![trelark regional controls bug 3](https://cloud.githubusercontent.com/assets/5599436/6568870/8ff9b2e8-c69c-11e4-96cd-1359a41355f3.png)

**Comment by Eluvatar** [comment]
NS++ has been adding regional controls all along, you just didn't notice.

The regional controls page has always been visible to any nation: its
actions are however properly restricted.

NS++ does need new graphics for the controls page to better fit with the
other shiny links in Rift however, and when that is done I will close this
issue.

**Comment by nitro740** [comment]
Oh, it is just that I do not seem to recall seeing that option, and I have not been founder or delegate in a region before. That was what raised the red lights for me. Thank you.

**Comment by nitro740** [comment]
Ok, it is just that I have never been a Regional Delegate or Founder, so I
am unfamiliar with those buttons and their locations. That is what raised
the red flag for me. Thank you.
