### ISSUE TITLE
Unable To Post To Regional Message Board

### ISSUE THREAD

**Issue by blazeHTL** [NationStates/NationStatesPlusPlus#54]
I'm having difficulty changing details in my region I am in charge of and posting to the regional message board. Is there any way this can be fixed, and how can I turn off Nationstates++?

**Comment by Blattinum** [comment]
What browser are you using? Trying clearing your cache (Chrome: Menu>More tools. . .>Clear browsing data. . .) then `chrome://restart` to see if issues persist. 
***
As a far as "turning off", you can disable (Chrome: Menu>More tools. . .>Extensions—then uncheck Enable next to NationStates++). Refresh NationStates.net and NationStates++ should be disabled.
