### ISSUE TITLE
Region Settings Glitches

### ISSUE THREAD

**Issue by abidawe** [NationStates/NationStatesPlusPlus#59]
Glitch with IRC settings panel and sidebar makes some settings (Custom founder and delegate name as well as officers panel) inaccessible. 

Unable to find the panel for setting up a regional newspaper in the regional controls panel. 

NS++ Settings in general still don't load period making it impossible to resolve the issues on my own.

NS++ not functioning properly in these areas makes the only alternative (LibreNS++) impossible to use as well.

**Comment by Eluvatar** [comment]
Visual glitches should be fixed.
