### ISSUE TITLE
IRC setting Pop-up won't disappear, Some buttons overlap others 

### ISSUE THREAD

**Issue by ghost** [NationStates/NationStatesPlusPlus#61]
When trying to access regional controls, the IRC setting pop-up appears right over some of the information that I want to see. Also, some of the "buttons" are in illogical places, or overlap other buttons.
![screenshot 85](https://user-images.githubusercontent.com/31852002/30274856-2e3a9e92-96cd-11e7-9b72-60070b75f634.png)

**Comment by Eluvatar** [comment]
Should be fixed.
